name: Sync Header/Footer External CSS

on:
  schedule:
    - cron: '0 4 * * *'  # This schedules the workflow to run at 4:00 AM EST every day
  workflow_dispatch:

env:
  HEADERUI: 'https://www.walgreens.com/common/v1/headerui'
  FOOTERUI: 'https://www.walgreens.com/common/v1/footerui'

jobs:
  curl:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        # The bot user https://github.com/franklinbot4walgreens is used to commit the changes.
        # The personal access token was created from: https://github.com/settings/tokens
        # The token is stored in the secrets of the this repo.
        # See https://github.com/hlxsites/walgreens/settings/secrets/actions
        # More info: https://stackoverflow.com/a/72515781/79461
        token: ${{ secrets.BOT_ACCESS_TOKEN }}

    - name: Install jq
      run: |
        sudo apt-get update -y
        sudo apt-get install jq -y

    - name: Fetch Header UI and Extract LSGCSS
      run: |
        curl ${{ env.HEADERUI }} | jq -r '.clientLSGCSSContent' > external-topic/external-styles/header-lsg-css-content.css

    - name: Fetch Header UI and Extract CSS
      run: |
        curl ${{ env.HEADERUI }} | jq -r '.clientCSSContent' > external-topic/external-styles/header-css-content.css

    - name: Fetch Footer UI and Extract LSGCSS
      run: |
        curl ${{ env.FOOTERUI }} | jq -r '.clientLSGCSSContent' > external-topic/external-styles/footer-lsg-css-content.css

    - name: Fetch Footer UI and Extract CSS
      run: |
        curl ${{ env.FOOTERUI }} | jq -r '.clientCSSContent' > external-topic/external-styles/footer-css-content.css

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        branch: main
        file_pattern: '*-css-content.css'
        commit_message: 'Update header/footer dynamic css'
