name: Sync Header/Footer External CSS

on:
  schedule:
    - cron: '0 4 * * *'  # This schedules the workflow to run at 4:00 AM EST every day

env:
  HEADERUI: 'https://www.walgreens.com/common/v1/headerui'
  FOOTERUI: 'https://www.walgreens.com/common/v1/footerui'

jobs:
  curl:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

    - name: Install jq
      run: |
        sudo apt-get update -y
        sudo apt-get install jq -y

    - name: Fetch Header UI and Extract LSGCSS
      run: |
        curl ${{ env.HEADERUI }} | jq -r '.clientLSGCSSContent' > external-styles/header-lsg-css-content.css

    - name: Fetch Header UI and Extract CSS
      run: |
        curl ${{ env.HEADERUI }} | jq -r '.clientCSSContent' > external-styles/header-css-content.css

    - name: Fetch Footer UI and Extract LSGCSS
      run: |
        curl ${{ env.FOOTERUI }} | jq -r '.clientLSGCSSContent' > external-styles/footer-lsg-css-content.css

    - name: Commit files
      run: |
        git config --local user.name  ${{ github.actor }}
        git config --local user.email "<>"
        git add .
        git commit -m "Update header-lsg-css-content.css, header-css-content.css, and footer-lsg-css-content.css"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.BOT_ACCESS_TOKEN }}
        branch: main
        force: true
