name: Sync Header/Footer External CSS

on:
  schedule:
    - cron: '0 4 * * *'  # This schedules the workflow to run at 4:00 AM EST every day
env:
  HEADERUI: 'https://www.walgreens.com/common/v1/headerui'
  FOOTERUI: 'https://www.walgreens.com/common/v1/footerui'

jobs:
  curl:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

    - name: Install jq
      run: |
        sudo apt-get update -y
        sudo apt-get install jq -y

    - name: Fetch Header UI and Extract LSGCSS
      run: |
        curl ${{ env.HEADERUI }} | jq -r '.clientLSGCSSContent' > external-styles/header-lsg-css-content.css

    - name: Fetch Header UI and Extract CSS
      run: |
        curl ${{ env.HEADERUI }} | jq -r '.clientCSSContent' > external-styles/header-css-content.css

    - name: Fetch Footer UI and Extract LSGCSS
      run: |
        curl ${{ env.FOOTERUI }} | jq -r '.clientLSGCSSContent' > external-styles/footer-lsg-css-content.css

    - name: Configure git
      run: |
        git config user.name "GitHubActions"
        git config user.email "<>"

      - name: Commit and Push Changes
      uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update header-lsg-css-content.css, header-css-content.css, and footer-lsg-css-content.css"
          file_pattern: "external-styles/*.css"
