name: Sync Header/Footer External CSS

on:
  schedule:
    - cron: '0 4 * * *'  # This schedules the workflow to run at 4:00 AM EST every day

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install jq
      run: |
        sudo apt-get update -y
        sudo apt-get install jq -y

    - name: Fetch Header UI and Extract LSGCSS
      run: |
        curl https://www.walgreens.com/common/v1/headerui | jq -r '.clientLSGCSSContent' > external-styles/header-lsg-css-content.css

    - name: Fetch Header UI and Extract CSS
      run: |
        curl https://www.walgreens.com/common/v1/headerui | jq -r '.clientCSSContent' > external-styles/header-css-content.css

    - name: Fetch Footer UI and Extract LSGCSS
      run: |
        curl https://www.walgreens.com/common/v1/footerui | jq -r '.clientLSGCSSContent' > external-styles/footer-lsg-css-content.css

    - name: Commit and Push Changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Update header-lsg-css-content.css, header-css-content.css, and footer-lsg-css-content.css"
        git push
